name: OpenSTL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - nni
  - numpy
  - hickle
  - pip
  - python
  - pytorch
  - xarray==0.19.0
  - pip:
    - decord
    - fvcore
    - lpips
    - pandas
    - scikit-image<=0.19.3
    - timm<=0.6.11
    - tqdm
prefix: /opt/anaconda3/envs/openstl