name: OpenSTL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy
  - hickle
  - pip
  - python<=3.10.8
  - pytorch-lightning<=1.9.5
  - pytorch<=2.1.1
  - xarray==0.19.0
  - pip:
    - decord
    - fvcore
    - lpips
    - pandas
    - scikit-image<=0.19.3
    - timm<=0.6.11
    - tqdm
    - einops
prefix: /opt/anaconda3/envs/openstl